### ISSUE TITLE
Add Windows setup information in Chinese

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack-documentation#31]
Note: This issue already has a volunteer

It would be great to have some learning resources in Chinese! Here are the suggested steps to add a new article to these docs:

- Create a folder called `chinese` within `guides/release`
- in that new directory make a file called `windows-setup.md` or similar, and a file called `index.md`
- Edit `pages.yml` to include the section and pages (example below)
- Add content to windows-setup
- In index.md, add one or two sentences that are a welcome message. An index.md file is required for the new section to render.
- Add any images you need in `public/images`

Example pages.yml
```
- title: "Chinese Learning Resources"
  url: "chinese"
  pages:
    - title: "Page title goes here"
      url: "index"
    - title: "Page title goes here"
      url: "windows-setup"
```

Thank you for the help!
